In [47]:
import numpy as np
import os
import torchvision.datasets as datasets
import torchvision.transforms as tf
import torch
from torch.autograd import Variable
import torch.nn as nn
import matplotlib.pyplot as plt

from trainer import trainer
from model import convnet
from dataset import mnist
from config import Config

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [48]:
cnn_model = trainer(model=convnet(batch_size=100,
                                  std=0.5),
                    seed=Config.seeds[0],dataset = mnist,configs = Config())

/Users/harisghafoor/anaconda3/envs/cv_seg/lib/python3.11/site-packages/torchvision/datasets/mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


In [49]:
train_loader,test_loader,idx = cnn_model.prepare_dataloader()

In [4]:
cnn_model.fit(train_loader= train_loader,
              test_loader=test_loader,
              )

tensor([0.])
tensor([0.])
tensor([0.])
tensor([2.1849])
tensor([0.])
tensor([0.])


RuntimeError: The size of tensor a (100) must match the size of tensor b (0) at non-singleton dimension 0